### ISSUE TITLE
Do we need to make a Quarto extension?

### ISSUE THREAD

**Issue by jhelvy** [jhelvy/surveydown#31]
One thing I've been thinking about is whether or not we should make a Quarto extension for surveydown. 

The main purpose would be to simplify the yaml. Right now we have this:

```
---
format: 
  html:
    section-divs: false
execute:
  echo: false
server: shiny
include-before-body: 
  - www/hide_pages.js
  - www/update_progress.js
theme: [united, www/surveydown.scss]
filters: [www/progressbar.lua]
barposition: "top" # top (default), bottom, or none
barcolor: "theme" # theme (default) or a hex code
---
```

I'd like to get it down to something like this:

```
---
format: 
  surveydown:
    barposition: "top" # top (default), bottom, or none
    barcolor: "theme" # theme (default) or a hex code
theme: [united, www/surveydown.scss]
---
```

Here if we had a `surveydown` quarto extension, we could nest some of the survey options like `barposition` and `barcolor` inside the `surveydown` format like in the above example and also eliminate the need to specify the js and lua filters (that would all be loaded in the `surveydown` extension format).

Another thought though is that perhaps we could solve a lot of this consolidation within the {surveydown} R package that we'll eventually make. For example, I noticed in the [{shinysurveys} package](https://github.com/jdtrat/shinysurveys), the author uses a `shiny::includeScript()` function to include some javascript files, like [this](https://github.com/jdtrat/shinysurveys/blob/main/R/func_survey-output.R#L218-L219). Maybe that could be used somewhere to avoid having the `include-before-body` part for the JS in the yaml? Then the only other part remaining is the lua filter for the progressbar. If there's a way to incorporate the progress bar without the lua filter, then we could put the `barposition` and `barcolor` options down in the `sd_config()` function and remove the need for all of that in the yaml. Then the yaml  would look something like this:

```
---
format: 
  html:
    section-divs: false
execute:
  echo: false
server: shiny
theme: [united, www/surveydown.scss]
---
```

That's all pretty standard stuff and we wouldn't need a separate Quarto extension. I kind of prefer this approach, but I'm not sure if we can solve the JS and progressbar parts. 

My main concern about developing a Quarto extension is that it's yet another setup step that users would have to remember to do for everything to work, and that's kind of annoying. It'd be nicer if they only had to install a {surveydown} R package and then just use a yaml template like the one above.
